title: 'Jonathan Eaves'
default_lang: en
author:
  name: Jonathan
  email: jdeaves@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'This is my metadata, but it used to be: (Grav is an easy to use, yet powerful, open source flat-file CMS)'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
